--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/95CivicSi/TestVirionForms
build-by-default: true
branches:
- master
projects:
  TestVirionForms:
    path: ""
    libs:
      - src: BreathTakinglyBinary/libDynamicForms/libDynamicForms
        version: ^1.1.0
    lint:
      phpstan: false
...
